### ISSUE TITLE
Freeze execution on iteration while error.

### ISSUE THREAD

**Issue by M-O-Z-G** [jadejs/jade#2006] opened 2015-06-26 07:19 UTC
If for one reason or another error occurs in the syntax of the iteration, it freezes the compiler process forever.

It's happening everywhere, even on [Demo Page]  *hang up browser process*
It would be good to display the error to console in such cases, otherwise I have to kill the browser process and/or restart the watchers in Gulp.

For example:
```jade
- var n = 0
ul
  while n < 4
    //- Freeze process forever
    li= n
```

[Demo Page]:http://jade-lang.com/demo/

**Comment by TimothyGu** [comment] 2015-06-26 09:01
> If for one reason or another error occurs in the syntax of the iteration

How is this a syntax error?

**Comment by M-O-Z-G** [comment] 2015-06-26 10:00
For example: if type by hands "while" in real-time preview, you typing:
```sh
...
while i < #and compiler hangs process (browser/terminal etc.), you just can't finish output.
```

Or if using auto-save and watcher with live-preview.

It's clear that in fact it is not a error, just an infinite loop. But it would be nice not run it if occurs, and provide warning to console, like other errors. Otherwise, just don't monitor the situation, why the task in the stack hangs infinitely and where. 

It's just an idea, I'm not saying that it is life-saving option. I noticed that when testing some outputs.

**Comment by jeromew** [comment] 2015-06-27 00:52
the closest i have seen so far relates to https://github.com/ForbesLindesay/halting-problem ; I am not sure where you would integrate this in the tool chain.
it would not catch all the halting scenarios but could maybe catch some of the editing scenario that you mention.

**Comment by TimothyGu** [comment] 2015-06-27 02:48
Duplicate of #1825.

**Closed by TimothyGu** 2015-06-27 02:48 UTC
