### ISSUE TITLE
This "missing space before text" warning really matters?

### ISSUE THREAD

**Issue by pateketrueke** [jadejs/jade#1872] opened 2015-02-19 05:13 UTC
OK, I'm bit frustrated, I like a lot Jade, and I like a lot mustache-like template engines, also I like a lot piping my templates this way: `my_view.js.ract.jade`

Wich would render first Jade, then pass out the html to Ractive's compile method to finally save to disk as plain old Javascript file.

Why this is annoying to me?

**my_view.js.ract.jade**

```jade
div
  {{#block}}
  span {{value}}
  {{/block}}
```

This compiles perfectly but `console.log()`s a "Warning", I've ended up with tons of templates with "|" everywhere:

```jade
div
  |{{#block}}
  span {{value}}
  |{{/block}}
```

Jade now is Ugly Betty.

Since both compiles fine I don't understand my issue yet.

I'd mean, it would be amazing to allow mustache-like syntax since it does not hurts?

**Comment by TimothyGu** [comment] 2015-03-01 18:05
Have you tried [react-jade](https://github.com/jadejs/react-jade)? I feel that it might serve your purpose better than adding this hack.

**Comment by pateketrueke** [comment] 2015-03-01 18:16
That looks nice but isn't [RactiveJS](http://www.ractivejs.org/), both are not the same thing.

I'm no trying to change technology/language only for this lack of support, or you think I must do instead?

Another example would be `sample.js.hbs.jade` which compiles rendered html from jade into handlebars, or can be Dust, Mustache, etc.

**Comment by TimothyGu** [comment] 2015-03-01 18:22
Oh oops. But in any case why are you doing this?

```jade
div
  if block
    span #{value}
```

works even better.

**Comment by pateketrueke** [comment] 2015-03-01 21:23
That's OK for Jade only, but that is not [my issue](https://github.com/gextech/tarima/commit/2341af32d3301d742fc3e5f3a5ce3cccc13d55f4).

I'm just using Jade to easily write HTML (which is the biggest feature of Jade), then take the generated markup and pre-compiling with another templating engine for client-side render, etc.

**Comment by full-stack-ex** [comment] 2015-03-04 17:22
A variation of the problem: same warning spams the log whenever jade sees a mixin like this:

    +MY_MIXIN(fo, baar)

Appeared a few releases ago.

**Comment by full-stack-ex** [comment] 2015-03-04 17:42
An update: it may be a wrong message.
The warning disappeared when we removed EXTRA spaces and tabs at the end of the line.

**Comment by TimothyGu** [comment] 2015-03-22 17:16
@full-stack-ex can you give an example to reproduce this problem?

**Comment by full-stack-ex** [comment] 2015-03-22 18:03
Sorry, not exactly the one I observed: it's in proprietary code. Let's 
try using this first.

This analog gives me different diagnostics in the same situation. It 
used to be a warning on extra space. Now it's an error. Overall, there 
is some instability about this issue: in the original code, the 
diagnostics depended on whether there were empty lines around the line 
in question, etc.

The problem is with the trailing tab at the end of this line. Error 
disappears when the tab is removed:
         +TEST_MIXIN("Hello")    <---- HERE

The sample is below and attached:

mixin TEST_MIXIN(x)
     p #{x}

html
     body

         +TEST_MIXIN("Hello")

         p World!

---

Error: .../test.jade:7
     5|     body
     6|
   > 7|         +TEST_MIXIN("Hello")
     8|
     9|         p World!
     10|

unexpected text


     at Object.Lexer.fail (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/lexer.js:875:11)
     at Object.Lexer.next (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/lexer.js:934:15)
     at Object.Lexer.lookahead (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/lexer.js:113:46)
     at Parser.lookahead (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:102:23)
     at Parser.peek (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:79:17)
     at Parser.tag (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:751:22)
     at Parser.parseCall (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:615:10)
     at Parser.parseExpr (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:237:21)
     at Parser.block (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:707:25)
     at Parser.tag (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:816:24)
     at Parser.parseTag (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:737:17)
     at Parser.parseExpr (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:211:21)
     at Parser.block (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:707:25)
     at Parser.tag (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:816:24)
     at Parser.parseTag (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:737:17)
     at Parser.parseExpr (/home/igor/projects/Be With 
Kids/webapps/plan-and-activities/node_modules/jade/lib/parser.js:211:21)


Thank you,
Igor


On 03/22/2015 11:16 AM, Timothy Gu wrote:
>
> @full-stack-ex <https://github.com/full-stack-ex> can you give an 
> example to reproduce this problem?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jadejs/jade/issues/1872#issuecomment-84657095>.
>


mixin TEST_MIXIN(x)
	p #{x}

html
	body

		+TEST_MIXIN("Hello")	

		p World!

**Comment by full-stack-ex** [comment] 2015-03-22 18:19
... and when I added one more tab here, the error disappeared:
         +TEST_MIXIN("Hello")        <---- TWO TABS HERE OK; ONE CAUSES 
AN ERROR


Sorry, not exactly the one I observed: it's in proprietary code. Let's 
try using this first.

**Comment by TimothyGu** [comment] 2015-03-22 18:35
Yes I think I can reproduce this. It is not exactly under the scope of this bug as it refers to something else, so I have created #1898.

**Comment by full-stack-ex** [comment] 2015-03-22 18:42
Sorry, it's a rather big deal to reproduce the original bug without 
disclosing the proprietary code. But if you get stuck with the original 
one, please let me know and I'll do something about it.

It all looks "similar": some combinations of spaces, tabs and empty 
lines are not properly recognized by the parser. And it seems to depend 
on a larger context: the whole module where the problematic lines are 
located.

Igor

**Comment by TimothyGu** [comment] 2015-03-22 18:43
For **this** bug (@pateketrueke), I would close it as won't fix. It is simply too out-of-scope for Jade.

**Closed by TimothyGu** 2015-03-22 18:43 UTC
