### ISSUE TITLE
Property 'visitundefined' of object #<Object> is not a function

### ISSUE THREAD

**Issue by cohom** [jadejs/jade#2039] opened 2015-08-07 11:50 UTC
Since I updated an entire express project with command

`~$ npm update`

The following error occurs every time I access to the top page.

> ```
> TypeError: Property 'visitundefined' of object #<Object> is not a function

> Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
>    at Object.Compiler.visitNode (/PROJECT_ROOT/node_modules/jade/lib/compiler.js:225:37)
>    at Object.Compiler.visit (/PROJECT_ROOT/node_modules/jade/lib/compiler.js:212:10)
>    at Object.Compiler.visitBlock (/PROJECT_ROOT/node_modules/jade/lib/compiler.js:295:12)
>    at Object.Compiler.visitNode (/PROJECT_ROOT/node_modules/jade/lib/compiler.js:225:37)
>    at Object.Compiler.visit (/PROJECT_ROOT/node_modules/jade/lib/compiler.js:212:10)
>    at Object.Compiler.compile (/PROJECT_ROOT/node_modules/jade/lib/compiler.js:66:10)
>    at parse (/PROJECT_ROOT/node_modules/jade/lib/index.js:114:19)
>    at Object.exports.compile (/PROJECT_ROOT/node_modules/jade/lib/index.js:205:16)
>    at handleTemplateCache (/PROJECT_ROOT/node_modules/jade/lib/index.js:174:25)
>    at Object.exports.renderFile (/PROJECT_ROOT/node_modules/jade/lib/index.js:380:10)
>    at View.exports.renderFile [as engine] (/PROJECT_ROOT/node_modules/jade/lib/index.js:370:21)
>    at View.render (/PROJECT_ROOT/node_modules/express/lib/view.js:126:8)
>    at tryRender (/PROJECT_ROOT/node_modules/express/lib/application.js:639:10)
>    at EventEmitter.render (/PROJECT_ROOT/node_modules/express/lib/application.js:591:3)
>    at ServerResponse.render (/PROJECT_ROOT/node_modules/express/lib/response.js:961:7)
>    at module.exports (/PROJECT_ROOT/app.js:164:7)
> ```

For information, the versions of node packages are:
```
"express": "^4.12.4",
"jade": "~1.9.2"
```

"app.js" view engine setup parts (when I set the 'view engine' to 'ejs' and comment out the 'jade', the error disappeared):
```
app.engine('ejs', require('ejs').renderFile);
app.engine('jade', require('jade').__express);

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade'); // default
//app.set('view engine', 'ejs');
```

"app.js" the part the error encountered (this snippet shows not that this is the cause of the issue, it only triggers jade loads):

```
// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('jade/error', {
    message: err.message,
    error: {}
  });
});
```

Any idea?

**Comment by ForbesLindesay** [comment] 2015-08-07 12:58
Thanks for the detailed error report.  Unfortunately I'm not able to reproduce this.  Is there any chance you could provide a sample of the jade code that causes this bug?

One thing you could try, in order to narrow down which lines jade is failing on, is to update [this function](https://github.com/jadejs/jade/blob/1.9.2/lib/compiler.js#L224-L226) in jade/lib/compiler.js as follows:

```diff
  visitNode: function(node){
+   console.log(node);
    return this['visit' + node.type](node);
  },
```

You can then look at the last couple of nodes that are logged to see what the value of the `line` and `filename` properties is.

This is definitely a bug in jade, rather than your code, so I really appreciate your help in reporting it.

**Comment by cohom** [comment] 2015-08-10 02:21
I found extended native array crushes the jade somehow.

```
Array.prototype.arrayed = function(){
	var self = this;
 	return Object.keys(self).map(function(v,i){ return self[v]; });
}
```

Here is what the `node' shows:

```
node { nodes: 
   [ { [Function] key: 'arrayed', extend: [Function] },
     { val: 'html',
       line: 1,
       filename: '/PROJECT_DIR/views/jade/layout.jade' },
     { attributeNames: [Object],
       attrs: [Object],
       attributeBlocks: [],
       name: 'html',
       block: [Object],
       selfClosing: false,
       line: 2,
       filename: '/PROJECT_DIR/views/jade/layout.jade' } ],
  line: 0,
  filename: '/PROJECT_DIR/views/jade/layout.jade' }
node function (){
	var self = this;
	return Object.keys(self).map(function(v,i){ return self[v]; });
}
```

**Comment by TimothyGu** [comment] 2015-09-17 05:39
This is obviously a result of a bad practice from the user. Thus closing.

**Closed by TimothyGu** 2015-09-17 05:39 UTC
Labels: bug
