### ISSUE TITLE
unexpected token "pipeless-text" in 1.5.0

### ISSUE THREAD

**Issue by trentmillar** [jadejs/jade#1628] opened 2014-08-14 17:49 UTC
Any ideas? There are no trailing spaces after the `<br/>`, which I found mentioned in a previous issue

>Error Details

```
Error: c:\bb\shenanigan-web\templates\layouts\doc.jade:149

147| .description 
148| h4 Downloads 
>149| p Download the #{brand} SDKs for your game platform.`<br/>`
150| a(href='/en/downloads') Downloads 
151| 
152| //- TURF THIS	

unexpected token "pipeless-text"
at Parser.parseExpr (c:\bb\shenanigan-web\node_modules\jade\lib\parser.js:252:15)
at Parser.parse (c:\bb\shenanigan-web\node_modules\jade\lib\parser.js:122:25)
at Parser.parse (c:\bb\shenanigan-web\node_modules\jade\lib\parser.js:131:24)
at parse (c:\bb\shenanigan-web\node_modules\jade\lib\jade.js:95:21)
```

**Comment by eddiemonge** [comment] 2015-01-06 19:13
I get this when using marked with the following code:

```
h1.page-header OAuth 2

:markdown

  ### Description
```

deleting the blank line after `:markdown` gets rid of the error but that seems to not be ideal. Probably related to #1588

**Comment by eddiemonge** [comment] 2015-01-07 00:15
Better visibility to me. I like white-space :turtle:

**Comment by ForbesLindesay** [comment] 2015-06-12 13:50
Duplicate of #1588

**Closed by ForbesLindesay** 2015-06-12 13:50 UTC
Labels: bug
