### ISSUE TITLE
Inline CSS before compilation

### ISSUE THREAD

**Issue by njakob** [jadejs/jade#2146] opened 2015-10-26 15:55 UTC
I'm trying to create a pipeline with Jade in order to compile templates for emails. To achieve that, it is necessary to inline the CSS inside the templates before the compilation pass.

Since the output of a template is obviously a JS function, it is not possible to use standard tools such as Premailer or Juice on a HTML document.

What is the best option to implement such feature ?

**Comment by TimothyGu** [comment] 2015-10-26 16:57
Includes?

```jade
style
  include a.css
```

**Comment by njakob** [comment] 2015-10-26 17:15
By inlining, I meant inline the CSS directly inside the tags. For instance,

```css
p.hello {
  color: red;
}
```

```jade
style
    include a.css
p(class='hello') world
```

will produce to following output:

```html
<style>
  p.hello {
    color: red;
  }
</style>
<p class="hello">world</p>
```

And my target is to produce the following output:

```html
<p style="color: red">world</p>
```

**Comment by ForbesLindesay** [comment] 2015-10-27 13:22
For that, you should pass the output of jade through https://www.npmjs.com/package/juice which will inline the css into the `style` attribute.  You can do this on the html output of jade.  If you need to do this at compile time (e.g. you are having performance issues with running juice) You would have to write your own jade plugin and use jade 2.0.0 (which should be released in the next week or so).  You would also need to write your own CSS selector engine (similar to cheerio) but based on the jade AST, so this would be a lot of work and you should only undertake it if you have really serious performance issues that you **know** are caused by juice.

**Closed by ForbesLindesay** 2015-10-27 13:22 UTC

**Comment by insetCoad** [comment] 2016-10-09 10:31
**You Can do this .** 
`.abs-Main-Full(style="left: 100px")`

**Comment by ChrisCooney** [comment] 2018-03-01 19:06
👍 This would be amazing, we're seeing some serious API performance hits by having to run Juice at runtime instead of at compile time.

**Comment by ForbesLindesay** [comment] 2018-03-02 18:08
You could write a plugin :)

**Comment by ChrisCooney** [comment] 2018-03-02 20:25
It's mostly written! The only thing I've failed to find is a way to write an AST hierarchy back to .pug file syntax. Is there anything out there at the moment?

**Comment by ChrisCooney** [comment] 2018-03-03 11:30
Scratch that, used generate code + loader to create me a nice pug function. The only thing I need to work out is how to add in options?

**Comment by ForbesLindesay** [comment] 2018-03-04 00:34
Did you see we now support true "plugins" (e.g. https://github.com/pugjs/pug-plugin-debug-line) as well as just using the lexer, parser etc. to build your own adapted version of pug.

**Comment by ChrisCooney** [comment] 2018-03-04 15:28
Just a quick update, having to hang up my hat on this one. The issue I got was the one you mentioned above @ForbesLindesay ,it's very difficult to know what styles a node is using without a CSS selector and trying to guess it within an AST is just too unreliable for anything production ready. Unless anyone can think of a way around this I'm pretty stuck.

**Comment by ffMathy** [comment] 2018-12-13 12:51
What a shame @ChrisCooney. Any way to share your progress?

**Comment by yairEO** [comment] 2022-03-12 17:06
I would very much like also an inline HTML injection of CSS
