### ISSUE TITLE
Passing Angular JS value into Jade Variable

### ISSUE THREAD

**Issue by rasekar2000** [jadejs/jade#2015] opened 2015-07-09 22:52 UTC
http://stackoverflow.com/questions/31226855/multiple-attribute-and-values-dynamic-in-angularjs-from-jade-template

I put my question with the controller / jade in the plunkr
http://plnkr.co/edit/T0JkSK6iybKBHhkGdlfL?p=preview

Objective is to pass the $scope.attrib value into the JADE which is waiting for additional attributes from $scope.attrib.

So, if you can just fix the current Plunkr's code line number 13, that would be great.

```jade
|my-directive(two="test3")&attributes(#{attrib})
```

Thanks and Regards,
Raj

**Comment by ForbesLindesay** [comment] 2015-10-05 12:43
It can't be done.  The jade gets rendered without any knowledge of angular data.  You would have to find a way of using angular to spread the attributes.

I'm closing this as it's not a bug in jade, feel free to continue commenting/discussing though.

**Closed by ForbesLindesay** 2015-10-05 12:43 UTC

**Comment by schechter** [comment] 2016-04-07 03:08
This is possible, or I'm not understanding the question.
```
.some-div  
    a(ng-click='myCtrl.doSomething()',
      ng-class="{'conditional-class': myCtrl.bar() }") {{ myCtrl.foo.label }}
```
generates
```
<div class="some-div">
    <a ng-click="myCtrl.doSomething()" ng-class="{'conditional-class': myCtrl.bar() }">{{ myCtrl.foo.label }}</a>
</div>
```

What seems to be impossible, but seem like it should be supported being able to do something like the above with mixins.
