### ISSUE TITLE
Missing space after inline comment

### ISSUE THREAD

**Issue by PinkyJie** [jadejs/jade#1942] opened 2015-04-23 05:47 UTC
`// build:css static/styles/lib.css` => `<!-- build:css static/styles/lib.css-->`

The correct comment should be `<!-- build:css static/styles/lib.css -->`, notice the space after `lib.css`. This is a minor issue, but sometimes it can cause [gulp-useref](https://www.npmjs.com/package/gulp-useref) failed to inject the js/css into the html file. This issue is also reported in gulp-inject repo, see https://github.com/klei/gulp-inject/issues/56 

Could you consider to add a extra space after inline comment?

**Comment by shgtkshruch** [comment] 2015-05-15 09:45
:+1:

**Comment by ForbesLindesay** [comment] 2015-05-18 14:48
I would accept a pull request for this.

**Comment by ForbesLindesay** [comment] 2015-06-22 15:05
Interestingly, we currently let you not put a space on either side via:

```jade
//build:css static/styles/lib.css
```
```html
<!--build:css static/styles/lib.css-->
```

and you can put a space on both sides by adding a trailing space (I realise this is not ideal).  Anything we change here would give people less control over where they put white space around comments, which makes me unsure that we should change this.  It seems to me that the gulp plugins could be easily fixed.

**Comment by dwilt** [comment] 2015-07-23 23:32
:+1: I'm running into this _exact_ issue as well. Trying to use `gulp-useref` and it's breaking.

Trying to do:
```
// build:js
// bower:js
// endbower
// endbuild
```
and the output is:
```
<!-- build:js-->
<!-- bower:js-->
<!-- endbower-->
<!-- endbuild-->
```

**Comment by TimothyGu** [comment] 2015-07-23 23:42
@dwilt said:
> I also tried putting a trailing space behind build:js but that didn't work either. It seems to get removed when compiled.

Can't reproduce that here

```jade
doctype
html
  head
    // build:css css/combined.css 
    link(rel='stylesheet' href='css/one.css')
    link(rel='stylesheet' href='css/two.css')
    // endbuild 
  body
    // build:js scripts/combined.js 
    script(type='text/javascript' src='scripts/one.js')
    script(type='text/javascript' src='scripts/two.js')
    // endbuild 
```

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- build:css css/combined.css -->
    <link rel="stylesheet" href="css/one.css">
    <link rel="stylesheet" href="css/two.css">
    <!-- endbuild -->
  </head>
  <body>
    <!-- build:js scripts/combined.js -->
    <script type="text/javascript" src="scripts/one.js"></script>
    <script type="text/javascript" src="scripts/two.js"></script>
    <!-- endbuild -->
  </body>
</html>
```

(example from [gulp-useref](https://www.npmjs.com/package/gulp-useref))

**Comment by dwilt** [comment] 2015-07-23 23:45
Yes, I just discovered that when I put in a file path (in your example `css/combined.css` and  `scripts/combined.js`), it worked. But not without it.

**Comment by PinkyJie** [comment] 2015-07-24 02:08
Putting a trailing space at the end of the line is not allowed in my editor, and I think it's not a best practice, seems the best way to fix this issue is file a issue on the repo of `gulp-useref`.

**Comment by TimothyGu** [comment] 2015-08-28 00:13
> seems the best way to fix this issue is file a issue on the repo of `gulp-useref`.

+1. Closing.

**Closed by TimothyGu** 2015-08-28 00:13 UTC

**Comment by francisrod01** [comment] 2017-05-28 01:18
If I'm in dev environment, I don't want to combine scripts, so... I solved that with a spance after inline commented. See it below:

`// bower:css ` *(here a one space after)* as "// bower:css "
`// endinject ` *(here a one space after)*
`// inject:css ` *(here a one space after)*
`// endinject ` *(here a one space after)*

and the output is:

```
<!-- bower:css -->
<!-- endinject -->
<!-- inject:css -->
<!-- endinject -->
```
Enjoy!
