### ISSUE TITLE
Combination of mixin with &attributes and extend/include not working

### ISSUE THREAD

**Issue by jayliu50** [jadejs/jade#2081] opened 2015-09-09 18:10 UTC
I have the following test case failing with an error.

*error:*
```
     TypeError: undefined is not a function
      at Object.Compiler.visitNode (node_modules/jade-code-gen/index.js:277:37)
      at Object.Compiler.visit (node_modules/jade-code-gen/index.js:265:10)
      at Object.Compiler.visitBlock (node_modules/jade-code-gen/index.js:352:12)
      at Object.Compiler.visitNode (node_modules/jade-code-gen/index.js:277:37)
      at Object.Compiler.visit (node_modules/jade-code-gen/index.js:265:10)
      at Object.Compiler.compile (node_modules/jade-code-gen/index.js:101:10)
      at generateCode (node_modules/jade-code-gen/index.js:25:39)
      at compileBody (lib/index.js:86:14)
      at Object.exports.compile (lib/index.js:163:16)
      at Context.<anonymous> (test/run.js:37:19)
```

*test.jade*
```Jade
include auxiliary/mixin
extends auxiliary/template

block test
  +image('myimg.png')(class="with-border")
```

*auxiliary/mixin.jade*
```Jade
mixin image(src)
  img(cl-src=src)&attributes(attributes)
```

*auxiliary/template.jade*
```Jade
.contents
  block test
```

*test.html* (expected)
```html
<div class="contents">
  <img cl-src="myimg.png" class="with-border"/>
</div>
```

**Comment by TimothyGu** [comment] 2015-09-13 04:11
Thanks for this detailed ticket! This is actually caused by two different bugs in jade-linker:

1. `extends` should always be the first statement in a file, but Jade didn't error out under these circumstances.
2. Once the order was fixed in test.jade, inclusion was properly applied as the Include node changes to a Block in the AST, but the content of the Block is ignored during the application of `extends`.

Both of these two bugs are fixed by jadejs/jade-linker#9.

**Closed** 2015-10-01 07:47 UTC
