### ISSUE TITLE
Error: unexpected token "pipeless-text"

### ISSUE THREAD

**Issue by mirek** [jadejs/jade#1611] opened 2014-07-30 02:01 UTC
6|   script(type='text/javascript')
        7|     :coffeescript
      > 8| 
        9|       alert 1
        10| 
        11|   //- Pass groupId
    unexpected token "pipeless-text"

It seems that blank line (without spaces) after `:coffeescript` line throws pipeless-text error.

This template is fine for example:

    script(type='text/javascript')
      :coffeescript
        # foo
        alert 1

jade@1.5.0

**Comment by ForbesLindesay** [comment] 2015-06-12 13:50
Duplicate of #1588

**Closed by ForbesLindesay** 2015-06-12 13:50 UTC
Labels: bug, filters
