### ISSUE TITLE
TokContext is not defined

### ISSUE THREAD

**Issue by ankitpatial** [jadejs/jade#1925] opened 2015-04-07 16:10 UTC
I am getting the following error for jade when starting my app.
i have installed latest nodes v0.12.2, jade v1.9.2

```
/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2200
  _classCallCheck(this, TokContext);/my-app
                        ^
ReferenceError: TokContext is not defined
    at new TokContext (/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2200:25)
    at Object../state (/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2209:11)
    at s (/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1:681)
    at /my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1:732
    at Object../expression (/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:80:21)
    at s (/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1:681)
    at e (/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1:852)
    at /my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1:870
    at a (/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1:150)
    at Object.<anonymous> (/my-app/submittals/node_modules/jade/node_modules/constantinople/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1:383)

Process finished with exit code 1
```

**Comment by ForbesLindesay** [comment] 2015-04-08 18:03
Delete /my-app/submittals/node_modules/jade then re-install.  If the problem persists, please provide a copy of the output of `npm ls` so I can tell exactly what versions of jade, constantinople, acorn-globals and acorn are being used.

**Comment by ForbesLindesay** [comment] 2015-04-08 23:48
Closing as I'm unable to reproduce.  Will reopen if you comment with more details.

**Comment by ankitpatial** [comment] 2015-04-09 05:36
Thanks for looking in.
Its good to close this issue.  Seems like other npm package **node-jsx** is the cause for it.

**Comment by toastman** [comment] 2015-05-08 13:33
This issue can be reproduced with
> node (0.12.2), 
> react (0.13.2),
> node-jsx (0.13.2), 
> jade (1.9.2)

but it works with node (0.11.2)

**Comment by ForbesLindesay** [comment] 2015-05-08 14:36
If you can provide a demo app that reproduces the issue I'll reopen.

**Comment by toastman** [comment] 2015-05-08 16:01
@ForbesLindesay Please look at 
https://github.com/toastman/jadeTokContext

**Comment by tuvistavie** [comment] 2015-06-02 11:59
I ran in the same problem.
I am not sure what the problem is, but using

```js
require('node-jsx').install({extension: 'jsx'});
```

instead of

```js
require('node-jsx').install();
```

was enough for me, as my JSX files are named with the jsx extension.

**Comment by ettysekhon** [comment] 2015-06-16 20:43
thanks @tuvistavi that solved it for me too.

**Comment by TimothyGu** [comment] 2015-06-17 00:40
This isn't Jade's bug, but rather jstransform's (jstransform is used in node-jsx).

Reduced test case:

```js
// npm i node-jsx acorn
require('node-jsx').install();
var acorn = require('acorn');
```

**Closed by TimothyGu** 2015-06-17 00:40 UTC
