### ISSUE TITLE
Bug with ' in inline code

### ISSUE THREAD

**Issue by paulpflug** [jadejs/jade#1929] opened 2015-04-13 10:33 UTC
`b ' ` yields `<b>'</b>`
but `#[b ']` results in `The end of the string was reached with no closing bracket found.`

the `'` can't be escaped, though.. ( `#[b \']` doesn't work either)

I think that is a bug ? shouldn't `#[]` work exactly like normal code?

**Comment by ForbesLindesay** [comment] 2015-04-13 13:32
Duplicate of #1723

**Closed by ForbesLindesay** 2015-04-13 13:32 UTC
Labels: bug
